#!/bin/bash
# Build the local model FMU with JModelica
# jm script customized for your system must be on your PATH
# compile_fmu.JModelica.py and mod_xml.JModelica.py must be on your PATH
# Run from the JModelica sub-directory of the model directory

# Set tool name
tool="JModelica"

# Set model name and file
model=Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case600FF
model_file=${MODELICA_BUILDINGS_LIB}/${model//.//}.mo

# Find the compile script
compile_fmu_name=compile_fmu.$tool.py
compile_fmu=$(which $compile_fmu_name)
if [ "$compile_fmu" == "" ]; then
    echo "$compile_fmu_name not found on your PATH"
    exit 1
fi

# Compile the FMU
jm.$tool $compile_fmu $model $model_file $@

# Rename the FMU
mv -f ${model//./_}.fmu ${model##*.}.fmu
model=${model##*.}

# Add index comment lines to XML
if [ -f "$model.fmu" ]; then
    unzip -o $model.fmu modelDescription.xml
    cp -f modelDescription.xml modelDescription.orig.xml
    mod_xml.JModelica.py
    sleep 1 && touch modelDescription.xml # zip -f won't work if .xml time stamp matches .fmu
    zip -f $model.fmu
fi
