#!/bin/bash
# Build the local model FMU with JModelica
# jm script customized for your system must be on your PATH
# compile_fmu.JModelica.py and mod_xml.JModelica.py must be on your PATH
# Run from the JModelica sub-directory of the model directory

# Find tool name and dir
tool="JModelica"

# Find model name and dir
model="Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case600FF"

# Compile the Modelica file with JModelica
compile_fmu_name="compile_fmu.JModelica.py"
compile_fmu=$(which "$compile_fmu_name")
if [ "$compile_fmu" == "" ]; then
    echo "$compile_fmu_name not found on your PATH"
    exit 1
fi

# Compile the FMU
jm $compile_fmu $model $@

# Add index comment lines to XML
mdl="${model##*.}"
model="${model//./_}"
unzip -o $model.fmu modelDescription.xml
cp -f modelDescription.xml modelDescription.orig.xml
mod_xml.JModelica.py
sleep 1 && touch modelDescription.xml # zip -f won't work if .xml time stamp matches .fmu
zip -f $model.fmu
mv -f $model.fmu $mdl.fmu
