#!/bin/bash
# Build the local model FMU with OCT
# jm script customized for your system must be on your PATH
# compile_fmu.OCT.py and mod_xml.OCT.py must be on your PATH
# Run from the OCT sub-directory of the model directory

# Set tool name
tool="JModelica"

# Set model name and file
model=Buildings.Examples.VAVReheat.Guideline36
model_file=${MODELICA_BUILDINGS_LIB}/${model//.//}.mo

# Find the compile script
compile_fmu_name=compile_fmu.$tool.py
compile_fmu=$(which $compile_fmu_name)
if [ "$compile_fmu" == "" ]; then
    echo "$compile_fmu_name not found on your PATH"
    exit 1
fi

# Compile the FMU
jm.$tool.issue1129 $compile_fmu $model $model_file $@

# Rename the FMU
mv -f ${model//./_}.fmu ${model##*.}.fmu
